stages:
  - release

release_foundry_package:
  stage: release
  only:
    - tags
  image: 
    name: alpine:latest
    entrypoint: [""]
  before_script:
    - apk add --no-cache --upgrade bash curl jq
  script:
    - |
      COMPATIBILITY=$(jq '.compatibility' system.json)
      VERSION=$(jq -r '.version' system.json)
      SYSTEM_JSON_URL="$CI_PROJECT_URL/-/raw/$CI_COMMIT_TAG/system.json"

      echo "Extracted compatibility: $COMPATIBILITY"
      echo "Token: $FOUNDRY_RELEASE_TOKEN"
      echo "Curl body: $CURL_BODY"

      # Dry Run
      DRY_RUN_RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "https://api.foundryvtt.com/_api/packages/release_version/" \
        -H "Content-Type: application/json" \
        -H "Authorization: $FOUNDRY_RELEASE_TOKEN" \
        -d '{
          "id": "debilus",
          "dry-run": true,
          "release": {
            "version": "'$VERSION'",
            "manifest": "'$SYSTEM_JSON_URL'",
            "notes": "'$CI_PROJECT_URL'/-/releases/'$CI_COMMIT_TAG'",
            "compatibility": '"$COMPATIBILITY"'
          }
        }'
      )

      if [ "$DRY_RUN_RESPONSE" -eq 200 ]; then
        echo "Dry run successful, proceeding with actual release..."
        RUN_RESPONSE = $(curl -s -o response.json -w "%{http_code}" -X POST "https://api.foundryvtt.com/_api/packages/release_version/" \
          -H "Content-Type: application/json" \
          -H "Authorization: $FOUNDRY_RELEASE_TOKEN" \
          -d '{
            "id": "debilus",
            "dry-run": false,
            "release": {
              "version": "'$VERSION'",
              "manifest": "'$SYSTEM_JSON_URL'",
              "notes": "'$CI_PROJECT_URL'/-/releases/'$CI_COMMIT_TAG'",
              "compatibility": '"$COMPATIBILITY"'
            }
          }'
        )

        if [ "$RUN_RESPONSE" -eq 200 ]; then
          echo "Release $VERSION successful!"
        else
          echo "Release failed, aborting..."
          echo "Response: $(cat response.json)"
          exit 1
        fi

      else
        echo "Dry run failed, aborting..."
        echo "Response: $(cat response.json)"
        exit 1
      fi
