stages:
  - release

release_foundry_package:
  stage: release
  image: 
    name: alpine:latest
    entrypoint: [""]
  before_script:
    - apk add --no-cache curl jq # Ensure curl and jq are available
  script:
    - |
      # Assume system.json is in the root directory of your repository
      # Read and parse compatibility info using jq
      COMPATIBILITY=$(jq '.compatibility' system.json)
      VERSION=$(jq -r '.version' system.json)

      # Assuming COMPATIBILITY contains the needed object in the correct format
      echo "Extracted compatibility: $COMPATIBILITY"

      SYSTEM_JSON_URL="$CI_PROJECT_URL/-/raw/$CI_COMMIT_TAG/system.json"

      CURL_BODY='{
        "id": "debilus",
        "dry-run": true,
        "release": {
          "version": "'$VERSION'"
          "manifest": "'$SYSTEM_JSON_URL'",
          "notes": "'$CI_PROJECT_URL'/-/releases/'$CI_COMMIT_TAG'",
          "compatibility": '"$COMPATIBILITY"'
        }
      }'

      echo "Curl body: $CURL_BODY"
      echo "Token: $FOUNDRY_RELEASE_TOKEN"

      # Dry Run
      DRY_RUN_RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "https://api.foundryvtt.com/_api/packages/release_version/" \
        -H "Content-Type: application/json" \
        -H "Authorization: $FOUNDRY_RELEASE_TOKEN" \
        -d "$CURL_BODY"
      )

      if [ "$DRY_RUN_RESPONSE" -eq 200 ]; then
        echo "Dry run successful, proceeding with actual release..."
        # Actual Release
        #curl -s -X POST "https://api.foundryvtt.com/_api/packages/release_version/" \
        #  -H "Content-Type: application/json" \
        #  -H "Authorization: $FOUNDRY_RELEASE_TOKEN" \
        #  -d '{
        #    "id": "debilus",
        #    "dry-run": false,
        #    "release": {
        #      "version": "'$CI_COMMIT_TAG'",
        #      "manifest": "'$SYSTEM_JSON_URL'",
        #      "notes": "'$CI_PROJECT_URL'/-/releases/'$CI_COMMIT_TAG'",
        #      "compatibility": '"$COMPATIBILITY"'
        #    }
        #  }'
        echo "FAKE RELEASE - uncomment the above curl command to perform the actual release"
      else
        echo "Dry run failed, aborting..."
        echo "Response: $(cat response.json)"
        exit 1
      fi
